version: '3.7'
services:
  consul:
    container_name: consul
    image: consul
    command: agent -server -ui -node=server-1 -bootstrap-expect=1 -client=0.0.0.0
    ports:
      - 8500:8500
  
  sqlserver-cadastros:
    container_name: sqlserver-cadastros
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=BoaEntrega@2019
      - MSSQL_PID=Developer
      - MSSQL_SA_PASSWORD=BoaEntrega@2019
      - MSSQL_DATABASE=BoaEntrega
      - MSSQL_DATA_DIR=/var/opt/mssql
      - MSSQL_INIT_LOG_LEVEL=0
      - MSSQL_LOG_LEVEL=0
      - MSSQL_TCP_PORT=1433
      - MSSQL_TCP_PORT_EXTERNAL=1433
      - MSSQL_TCP_PORT_EXTERNAL_WEB=1433
      - MSSQL_TCP_PORT_WEB=1433
    ports:
      - 1433:1433

  sqlserver-notificacoes:
    container_name: sqlserver-notificacoes
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=BoaEntrega@2019
      - MSSQL_PID=Developer
      - MSSQL_SA_PASSWORD=BoaEntrega@2019
      - MSSQL_DATABASE=BoaEntrega
      - MSSQL_DATA_DIR=/var/opt/mssql
      - MSSQL_INIT_LOG_LEVEL=0
      - MSSQL_LOG_LEVEL=0
      - MSSQL_TCP_PORT=1434
      - MSSQL_TCP_PORT_EXTERNAL=1434
      - MSSQL_TCP_PORT_EXTERNAL_WEB=1434
      - MSSQL_TCP_PORT_WEB=1434
    ports:
      - 1434:1434      

  BoaEntrega.GSL.Identidade1:
    image: boaentrega/services/identidade:service
    build: 
      dockerfile: ./src/BoaEntrega.GSL.Identidade/Dockerfile
      context: .
    container_name: identidade1
    environment:
      - ConsulSettings__ServiceId=identidade-service-1
      - ConsulSettings__ServiceName=identidade-service
      - ConsulSettings__ServiceHost=identidade1
      - ConsulSettings__ServicePort=9004
      - ConsulSettings__ServiceDiscoveryAddress=http://consul:8500
    depends_on:
      - "consul"

  BoaEntrega.GSL.Identidade2:
    image: boaentrega/services/identidade:service
    build: 
      dockerfile: ./src/BoaEntrega.GSL.Identidade/Dockerfile
      context: .
    container_name: identidade2
    environment:
      - ConsulSettings__ServiceId=identidade-service-2
      - ConsulSettings__ServiceName=identidade-service
      - ConsulSettings__ServiceHost=identidade2
      - ConsulSettings__ServicePort=9004
      - ConsulSettings__ServiceDiscoveryAddress=http://consul:8500
    depends_on:
      - "consul"  
      - "identidade1"    

  BoaEntrega.GSL.Notificacoes:
    image: boaentrega/services/notificacoes:service
    build: 
      dockerfile: ./src/BoaEntrega.GSL.Notificacoes/Dockerfile
      context: .
    container_name: notificacoes
    environment:
      - ConsulSettings__ServiceId=notificacoes-service-1
      - ConsulSettings__ServiceName=notificacoes-service
      - ConsulSettings__ServiceHost=notificacoes
      - ConsulSettings__ServicePort=9003
      - ConsulSettings__ServiceDiscoveryAddress=http://consul:8500
    depends_on:
      - "consul"      

  BoaEntrega.GSL.Cadastros1:
    image: boaentrega/services/cadastros:service
    build: 
      dockerfile: ./src/Cadastros/BoaEntrega.GSL.Cadastros.WebApi/Dockerfile
      context: .
    container_name: cadastros1
    environment:
      - ConsulSettings__ServiceId=cadastros-service-1
      - ConsulSettings__ServiceName=cadastros-service
      - ConsulSettings__ServiceHost=cadastros1
      - ConsulSettings__ServicePort=9001
      - ConsulSettings__ServiceDiscoveryAddress=http://consul:8500
    depends_on:
      - "consul"  

  BoaEntrega.GSL.Cadastros2:
    image: boaentrega/services/cadastros:service
    build: 
      dockerfile: ./src/Cadastros/BoaEntrega.GSL.Cadastros.WebApi/Dockerfile
      context: .
    container_name: cadastros2
    environment:
      - ConsulSettings__ServiceId=cadastros-service-2
      - ConsulSettings__ServiceName=cadastros-service
      - ConsulSettings__ServiceHost=cadastros2
      - ConsulSettings__ServicePort=9001
      - ConsulSettings__ServiceDiscoveryAddress=http://consul:8500
    depends_on:
      - "consul"  

  BoaEntrega.GSL.ApiGateway:
    image: boaentrega/services/api-gateway:service
    build: 
      dockerfile: ./src/BoaEntrega.GSL.ApiGateway/Dockerfile
      context: .
    container_name: api-gateway
    environment:
      - GlobalConfiguration__Host=consul
      - GlobalConfiguration__Port=8500
    ports:
        - 9000:9000
    depends_on:
      - "consul"        

  eventstore.db:
    container_name: eventstore
    image: eventstore/eventstore:21.6.0-buster-slim
    environment:
      - EVENTSTORE_CLUSTER_SIZE=1
      - EVENTSTORE_RUN_PROJECTIONS=All
      - EVENTSTORE_START_STANDARD_PROJECTIONS=true
      - EVENTSTORE_EXT_TCP_PORT=1113
      - EVENTSTORE_HTTP_PORT=2113
      - EVENTSTORE_INSECURE=true
      - EVENTSTORE_ENABLE_EXTERNAL_TCP=true
      - EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP=true
    ports:
      - 1113:1113
      - 2113:2113
    
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:management 
    ports: 
      - 5672:5672
      - 15672:15672